import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import Providers from '@/components/Providers';
import MainLayout from '@/components/layout/MainLayout';
import "./globals.css";

export const metadata = {
  title: "Next.js + MUI Starter",
  description: "Generated by Antigravity",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider>
          <ThemeRegistry>
            <Providers>
              <MainLayout>
                {children}
              </MainLayout>
            </Providers>
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
